### ISSUE TITLE
Can't install sailfishos zip

### ISSUE THREAD

**Issue by fractal1510** [DeadSquirrel01/sailfishos-a5ultexx-releases#1]
[recovery.log](https://github.com/DeadSquirrel01/sailfishos-a5ultexx-releases/files/2310909/recovery.log)

**Comment by Kr1sh1** [comment]
I have same issue

**Comment by DeadSquirrel01** [comment]
That happens because the kernel of A5 twrp has OOM killer config that causes out of memory errors when unpacking big tar archives. You can try the twrp from here: https://github.com/DeadSquirrel01/lineage-15_a5_releases/releases/tag/20180210 
I don't remember if it was built with the minimal kernel config that hasnt the config that causes the error, if not i'll upload one

**Comment by fractal1510** [comment]
I'm already using recovery from that link, that means we need a new recovery with a valid config, please upload it when you can. Thanks.

**Comment by DeadSquirrel01** [comment]
You can use this: https://drive.google.com/file/d/1s6ZFvPQucQlYkKYeXzHilRJc6kDg7L9r/view?usp=drivesdk
It's a multirom recovery that i built some time ago from my halium-supported fork. (you cant install lineage 15.1 with it).
That's the one i always use to flash sailfish, so, it should work

Edit: to flash it go in twrp->advanced->terminal and run:
dd if=PATH_of_RECOVERY.img of=/dev/block/mmcblk0p17

**Comment by DeadSquirrel01** [comment]
Fixed in 20181114 release's twrp
